name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Use Node.js 16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@a9644610a0efe63542b1887c9317ce8628f56521
        with:
          server: s1.ct8.pl
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_nodejs/
          dry-run: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.cache/**
            **/.storybook/**
            **/app/**
            .babelrc
            .eslintrc.json
            .gitignore
            .pretterc.json
            codecov.yml
            jest.config.json
            jest.setup.ts
            LICENSE
            postcss.config.js
            README.MD
            remix.config.js
            remix.env.d.ts
            tailwind.config.js
            tsconfig.json

      - name: Build and restart
        uses: garygrossgarten/github-action-ssh@2b10f41b5a33808f6d24eafd253296766308b7c4
        with:
          command: |
            cd domains/${{ secrets.CT8_DOMAIN }}/public_nodejs/
            npm ci
            devil www restart ${{ secrets.CT8_DOMAIN }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD}}
          tryKeyboard: true
